### ISSUE TITLE
No vertigo-tabs available on Firefox 52? OS: Debian

### ISSUE THREAD

**Issue by forenbuddy** [idlewan/vertigo-tabs#10]
I do not seem to be able to open vertigo tabs in any way.

On Firefox 52 on Debian when adding sidebar button and clicking on it, I don't find 'vertigo-tabs'. Is this expected because of old version or a bug?

Ctrl-y opens a new tab, no vertigo-tabs.

**Comment by idlewan** [comment]
The extension is a WebExtension, and has only been developped/tested on Firefox v56, then v57+. Some or most of the extensions APIs might not have been there in v52. I recommend you take a look at legacy web extensions for your vertical tabs purposes (they should be marked as suched on addons.mozilla.org), or use an old version of TreeStyleTab.
